%% post process 
panel_post = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Post-Process ',...
'Position',[75 42 52 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');

%% udpate background 
panel_spatial = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Background ',...
'Position',[130 42 52 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');

%% post process 
panel_spatial = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Spatial',...
'Position',[75 29 52 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');
% 
%% udpate background 
panel_temporal = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Temporal ',...
'Position',[130 29 52 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');
% %%
% % pushbutton for choosing directory 
% push_dir = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','Directory',...
% 'Style','pushbutton',...
% 'Position',[2 9 11 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14, ...
% 'callback', 'push_dir_callback');
% 
% % 'edit' box for typing data directory 
% edit_dir = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String',dir_nm,...
% 'Style','edit',...
% 'Position',[14, 9, 50, 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','file_edit', ...
% 'FontSize', 14, ...
% 'callback', 'edit_dir_callback');
% 
% % push button for choosing data file 
% push_file = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','File',...
% 'Style','pushbutton',...
% 'Position',[2 7 11 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14, ...
% 'callback', 'push_file_callback');
% 
% % 'edit' box for typing file name
% edit_file = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','*.tif or *.mat',...
% 'Style','edit',...
% 'Position',[14, 7, 50, 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','file_edit', ...
% 'FontSize', 14, ...
% 'callback', 'edit_file_callback');
% 
% %% spatial information of the data 
% text_height = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','Height',...
% 'Style','pushbutton',...
% 'Position',[2 5 14 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14);
% 
% text_width = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','Width',...
% 'Style','pushbutton',...
% 'Position',[18 5 14 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14);
% text_frame = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','# Frame',...
% 'Style','pushbutton',...
% 'Position',[34 5 14 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14);
% text_Fs = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','Fs',...
% 'Style','pushbutton',...
% 'Position',[50 5 14 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14);
% 
% %% values 
% edit_height = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','0',...
% 'Style','edit',...
% 'Position',[2 3 14 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14);
% 
% edit_width = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','0',...
% 'Style','edit',...
% 'Position',[18 3 14 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14);
% edit_frame = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','0',...
% 'Style','edit',...
% 'Position',[34 3 14 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14);
% 
% edit_Fs = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String', 10,...
% 'Style','edit',...
% 'Position',[50 3 14 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14, ...
% 'callback', 'Fs=str2double(get(gco, ''string'')); neuron_raw.Fs = Fs;');
% 
% % calcium indicator
% text_indicator = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','Calcium Indicator',...
% 'Style','pushbutton',...
% 'Position',[2, 1 30 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14);
%  
% edit_indicator = uicontrol(...
% 'Parent',panel_data,...
% 'FontUnits',get(0,'defaultuicontrolFontUnits'),...
% 'Units','characters',...
% 'String','GCaMP6f',...
% 'Style','edit',...
% 'Position',[37 1 26.5 1.75],...
% 'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
% 'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
% 'Callback','%automatic',...
% 'Children',[],...
% 'ParentMode','manual',...
% 'Tag','data_dir',...
% 'FontSize',14, 'callback', 'neuron_raw.indicator=''GCaMP6f'';');

