%% panel for loading data
panel_load = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Load Data',...
'Position',[5 16 67 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');


% pushbutton for loading data  
push_load = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Load',...
'Style','pushbutton',...
'Position',[25 7 16 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',16, 'fontweight', 'bold', ...
'callback', 'push_load_callback;');

% pushbutton for displaying correlation image and PNR 
push_corr = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Corr. & PNR',...
'Style','pushbutton',...
'Position',[45 7 20 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',16, 'fontweight', 'bold', ...
'callback', 'push_corr_callback;');

% downsampling 
text_ds = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Downsample',...
'Style','text',...
'Position',[2 5 16 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

text_ssub = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','spatial',...
'Style','pushbutton',...
'Position',[20 5 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_ssub = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[32.6 5 7 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'neuron_raw.options.ssub=str2double(get(gco, ''string''));');


text_tsub = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','temporal',...
'Style','pushbutton',...
'Position',[43 5 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_tsub = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[56.5 5 7 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'neuron_raw.options.tsub=str2double(get(gco, ''string''));');

%frames 
text_temporal = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Frames',...
'Style','text',...
'Position',[2 2 16 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

text_begin = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','begin',...
'Style','pushbutton',...
'Position',[20 2.5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_begin = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[20, 0.5, 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', ['sframe=str2double(get(edit_begin, ''string''));', ...
'num2read=eframe-sframe+1; set(edit_total, ''string'', num2read);']);

text_end = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','end',...
'Style','pushbutton',...
'Position',[35 2.5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_end = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[35, 0.5, 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', ['eframe=str2double(get(edit_end, ''string''));', ...
'num2read=eframe-sframe+1; set(edit_total, ''string'', num2read);']);


text_total = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','total',...
'Style','pushbutton',...
'Position',[50 2.5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_total = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[50, 0.5, 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14,...
'callback', ['num2read=str2double(get(gco, ''string''));',...
'eframe=min(sframe+num2read-1, numFrame); set(edit_end, ''string'', eframe);']);
