%% panel for updating neuron parameters 
panel_neuron = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Neuron',...
'Position',[5 29 67 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');

% neuron size  
text_gsiz = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Size',...
'Style','pushbutton',...
'Position',[2 7 10 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

edit_gsiz = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 15,...
'Style','edit',...
'Position',[13 7 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

% gaussian width
text_gsig = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','sig',...
'Style','pushbutton',...
'Position',[20 7 10  1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

edit_gsig = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 4,...
'Style','edit',...
'Position',[31 7 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold', 'callback', 'edit_gsig_callback;');

%% searching method 
text_method = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Method',...
'Style','text',...
'Position',[2 4 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

radio_ellipse = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','ellipse',...
'Style','radiobutton',...
'value', 1, ...
'Position',[15 5 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'radio_ellipse_callback;');

text_ellipse = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','ratio',...
'Style','pushbutton',...
'Position',[30 5 10 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_ellipse = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',3,...
'Style','edit',...
'Position',[41 5 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

 radio_dilate = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','dilate',...
'Style','radiobutton',...
'value', 0, ...
'Position',[15 3 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14,...
'callback', 'radio_dilate_callback;');

text_dilate = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','radius',...
'Style','pushbutton',...
'Position',[30 3 10 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_dilate = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',3,...
'Style','edit',...
'Position',[41 3 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);