clear; clc; close all; 
default_options = CNMFSetParms(); 

%% PACKAGE FOLDER 
cur_cd = cd();      % current directory 
[temp, ~, ~] = fileparts(mfilename('fullpath')); 
cd(temp); cd ..;  
CNMFE_DIR = pwd(); 
cd(cur_cd); 

try
    load([CNMFE_DIR, filesep, '.dir.mat']); %load previous path
catch
    dir_nm = cd(); %use the current path
end

%% create main figure of the GUI window 
main_fig = figure(...
'Units','characters',...
'Position',[135 4 198 56],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','CNMF_E',...
'NumberTitle','off',...
'Resize','on',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'ScreenPixelsPerInchMode','manual',...
'ParentMode','manual',...
'HandleVisibility','callback',...
'Tag','figure1' );

%% panel for including all information of the raw data 
panel_data = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Raw Data',...
'Position',[5 42 67 13],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');

% pushbutton for choosing directory 
push_dir = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Directory',...
'Style','pushbutton',...
'Position',[2 9 11 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'push_dir_callback');

% 'edit' box for typing data directory 
edit_dir = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',dir_nm,...
'Style','edit',...
'Position',[14, 9, 50, 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Children',[],...
'ParentMode','manual',...
'Tag','file_edit', ...
'FontSize', 14, ...
'callback', 'edit_dir_callback');

% push button for choosing data file 
push_file = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','File',...
'Style','pushbutton',...
'Position',[2 7 11 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'push_file_callback');

% 'edit' box for typing file name
edit_file = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','*.tif or *.mat',...
'Style','edit',...
'Position',[14, 7, 50, 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Children',[],...
'ParentMode','manual',...
'Tag','file_edit', ...
'FontSize', 14, ...
'callback', 'edit_file_callback');

%% spatial information of the data 
text_height = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Height',...
'Style','pushbutton',...
'Position',[2 5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

text_width = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Width',...
'Style','pushbutton',...
'Position',[18 5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
text_frame = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','# Frame',...
'Style','pushbutton',...
'Position',[34 5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
text_Fs = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Fs',...
'Style','pushbutton',...
'Position',[50 5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

%% values 
edit_height = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[2 3 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_width = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[18 3 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
edit_frame = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[34 3 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_Fs = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 10,...
'Style','edit',...
'Position',[50 3 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'Fs=str2double(get(gco, ''string'')); neuron_raw.Fs = Fs;');

% calcium indicator
text_indicator = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Calcium Indicator',...
'Style','pushbutton',...
'Position',[2, 1 30 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_indicator = uicontrol(...
'Parent',panel_data,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','GCaMP6f',...
'Style','edit',...
'Position',[37 1 26.5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'callback', 'neuron_raw.indicator=''GCaMP6f'';');


%% parameters 
panel_neuron = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Neuron',...
'Position',[5 29 67 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');

% neuron size  
text_gsiz = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Size',...
'Style','pushbutton',...
'Position',[2 7 10 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

edit_gsiz = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 15,...
'Style','edit',...
'Position',[13 7 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

% gaussian width
text_gsig = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','sig',...
'Style','pushbutton',...
'Position',[20 7 10  1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

edit_gsig = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 4,...
'Style','edit',...
'Position',[31 7 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold', 'callback', 'edit_gsig_callback;');

%% searching method 
text_method = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Method',...
'Style','text',...
'Position',[2 4 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

radio_ellipse = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','ellipse',...
'Style','radiobutton',...
'value', 1, ...
'Position',[15 5 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'radio_ellipse_callback;');

text_ellipse = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','ratio',...
'Style','pushbutton',...
'Position',[30 5 10 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_ellipse = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',3,...
'Style','edit',...
'Position',[41 5 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

 radio_dilate = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','dilate',...
'Style','radiobutton',...
'value', 0, ...
'Position',[15 3 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14,...
'callback', 'radio_dilate_callback;');

text_dilate = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','radius',...
'Style','pushbutton',...
'Position',[30 3 10 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_dilate = uicontrol(...
'Parent',panel_neuron,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',3,...
'Style','edit',...
'Position',[41 3 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

%% panel for loading the data 
panel_load = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Load Data',...
'Position',[5 16 67 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');


% pushbutton for loading data  
push_load = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Load',...
'Style','pushbutton',...
'Position',[25 7 16 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',16, 'fontweight', 'bold', ...
'callback', 'push_load_callback;');

% pushbutton for displaying correlation image and PNR 
push_corr = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Corr. & PNR',...
'Style','pushbutton',...
'Position',[45 7 20 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',16, 'fontweight', 'bold', ...
'callback', 'push_corr_callback;');

% downsampling 
text_ds = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Downsample',...
'Style','text',...
'Position',[2 5 16 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

text_ssub = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','spatial',...
'Style','pushbutton',...
'Position',[20 5 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_ssub = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[32.6 5 7 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'neuron_raw.options.ssub=str2double(get(gco, ''string''));');


text_tsub = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','temporal',...
'Style','pushbutton',...
'Position',[43 5 12 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_tsub = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[56.5 5 7 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', 'neuron_raw.options.tsub=str2double(get(gco, ''string''));');

%frames 
text_temporal = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Frames',...
'Style','text',...
'Position',[2 2 16 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold');

text_begin = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','begin',...
'Style','pushbutton',...
'Position',[20 2.5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_begin = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[20, 0.5, 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', ['sframe=str2double(get(edit_begin, ''string''));', ...
'num2read=eframe-sframe+1; set(edit_total, ''string'', num2read);']);

text_end = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','end',...
'Style','pushbutton',...
'Position',[35 2.5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_end = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[35, 0.5, 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, ...
'callback', ['eframe=str2double(get(edit_end, ''string''));', ...
'num2read=eframe-sframe+1; set(edit_total, ''string'', num2read);']);


text_total = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','total',...
'Style','pushbutton',...
'Position',[50 2.5 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);
 
edit_total = uicontrol(...
'Parent',panel_load,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[50, 0.5, 14 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14,...
'callback', ['num2read=str2double(get(gco, ''string''));',...
'eframe=min(sframe+num2read-1, numFrame); set(edit_end, ''string'', eframe);']);

%% initialization  
panel_init = uipanel(...
'Parent',main_fig,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Initialization',...
'Position',[5 1 67 11],...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuipanelBackgroundColorMode'),...
'ParentMode','manual',...
'Tag','data_panel',...
'FontSize',18,...
'FontWeight','bold');

push_init = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Initialize A & C',...
'Style','pushbutton',...
'Position',[18 7 30 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',16, 'fontweight', 'bold', ...
'callback', 'push_init_callback;');

% debug mode 
debug_on = true; 
save_avi = false; 

check_debug = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','debug mode',...
'Style','checkbox',...
'value', 1, ...
'Position',[2 5 20 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold', ...
'callback', 'debug_on = get(check_debug, ''value'');');

check_saveavi = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','save AVI',...
'Style','checkbox',...
'value', 0, ...
'Position',[23, 5, 20, 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14, 'fontweight', 'bold',...
'callback', 'save_avi=get(check_saveavi, ''value'');');

%thresholds for detecting seed pixels 
text_mincorr = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 'min corr.',...
'Style','pushbutton',...
'Position',[2 3 15 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_mincorr = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', num2str(default_options.min_corr'),...
'Style','edit',...
'Position',[17.5 3 10 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14,...
'callback', 'neuron.options.min_corr= str2double(get(edit_mincorr, ''string'')));');

text_minpnr = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 'min PNR.',...
'Style','pushbutton',...
'Position',[30 3 15 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_minpnr = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', num2str(default_options.min_pnr'),...
'Style','edit',...
'Position',[45.5 3 10 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14,...
'callback', 'neuron.options.min_corr= str2double(get(edit_mincorr, ''string'')));');

%% 
text_patch = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', '# patch',...
'Style','pushbutton',...
'Position',[2 1 15 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_nr = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 2,...
'Style','edit',...
'Position',[17.5 1 3.5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

text_times = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 'X',...
'Style','edit',...
'Position',[21 1 3 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_nc = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 2,...
'Style','edit',...
'Position',[24 1 3.5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);


text_patch = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 'max # neuron',...
'Style','pushbutton',...
'Position',[30 1 20 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);

edit_K = uicontrol(...
'Parent',panel_init,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String', 500,...
'Style','edit',...
'Position',[50 1 5 1.75],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'BackgroundColorMode',get(0,'defaultuicontrolBackgroundColorMode'),...
'Callback','%automatic',...
'Children',[],...
'ParentMode','manual',...
'Tag','data_dir',...
'FontSize',14);